version: 1.0.{build}
environment:
  Platform: Win32
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PlatformToolset: v141
    Configuration: Release
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PlatformToolset: v141
    Configuration: Debug
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    PlatformToolset: v140
    Configuration: Release
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    PlatformToolset: v140
    Configuration: Debug
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    PlatformToolset: LLVM-vs2014
    Configuration: Release
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    PlatformToolset: LLVM-vs2014
    Configuration: Debug
matrix:
  allow_failures:
    - PlatformToolset: LLVM-vs2014
install:
- cmd: git submodule update --init --recursive
build_script:
- ps: >-
    $command = 'msbuild "vc14/columns_ui-public.sln" /m /verbosity:normal /p:PlatformToolset=' + $Env:PlatformToolset + ' /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"'

    iex $command

    $host.SetShouldExit($LASTEXITCODE)
